version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: orderbook
      POSTGRES_PASSWORD: orderbook
      POSTGRES_DB: orderbook
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderbook"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=orderbook
      - DB_PASSWORD=orderbook
      - DB_NAME=orderbook
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/go/src/app/.env

volumes:
  postgres_data: